### ISSUE TITLE
`destination-claim` is a dangerous degree of freedom

### ISSUE THREAD

**Issue by mathias-arm** [SimonFrost-Arm/draft-frost-rats-eat-collection#11]
One example is setting `destination-claim` to EAT `nonce`, I can use an EAT token from an entity that thinks it is participating in a remote attestation protocol to look like it is the top-level signer of a collection.

A dedicated claim for the "binder destination" would allow for explicit participation in the binding from the top-level signer. That claim should be multi-valued if we want to support the full potential scope that `destination-claim` brings.

Leaving `destination-claim`, potentially as optional (absence of which would imply dedicated claim defined in previous paragraph), would require some fuzzy requirement that the claim "cannot be abused". This requirement might prove very difficult to automate.

**Comment by SimonFrost-Arm** [comment]
I'm not sure that the dedicated claim will help as an attacker could create a scenario where they try to manipulate that claim. I think that any implementation for binding claims needs to consider the data passing mechanism for that binding and how it might be attacked/protected. I've added a statement to that effect to the security considerations.
Can you have a look at https://github.com/SimonFrost-Arm/draft-frost-rats-eat-collection/pull/13 please & see if I've covered that sufficiently?
