### ISSUE TITLE
Need to register a suitable Media Type for EAT Collection

### ISSUE THREAD

**Issue by yogeshbdeshpande** [SimonFrost-Arm/draft-frost-rats-eat-collection#14]
EAT Collection draft, needs to have a suitable Media Type to indicate that the associated content pertains to an EAT Collection

**Comment by yogeshbdeshpande** [comment]
This change is required so that the CCA implementation is inline with the specification

**Comment by thomas-fossati** [comment]
To add a bit more context:

The EAT collection is a new top-level object in the EAT type system (see [here](https://www.ietf.org/archive/id/draft-ietf-rats-eat-media-type-01.html#name-eat-types-2) for how it looks like at the moment.). Therefore, similar to [`eat-cwt` & co](https://www.ietf.org/archive/id/draft-ietf-rats-eat-media-type-01.html#section-6), a new media type needs to be defined.

Note that the new media type can be [parametrised based on profile](https://www.ietf.org/archive/id/draft-ietf-rats-eat-media-type-01.html#section-3), which allows us to use it when submitting CCA tokens to Veraison's for verification without the need to register a CCA-specific media type.
